apiVersion: apps/v1
kind: Deployment
metadata:
  name: templeton-incremental
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: templeton-incremental
  template:
    metadata:
      labels:
        de-app: templeton-incremental
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: de-app
                operator: In
                values:
                - templeton-incremental
            topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: templeton.yaml
                path: templeton-incremental.yaml
      containers:
      - name: templeton-incremental
        image: harbor.cyverse.org/de/templeton
        resources:
          requests:
            cpu: "2m"
            memory: "128Mi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "100m"
            memory: "256Mi"
            ephemeral-storage: "1Gi"
        env:
          - name: OTEL_TRACES_EXPORTER
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_TRACES_EXPORTER
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
        args:
          - --mode
          - incremental
          - --config
          - /etc/iplant/de/templeton-incremental.yaml
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: timezone
            mountPath: /etc/timezone
            subPath: timezone
          - name: service-configs
            mountPath: /etc/iplant/de
            readOnly: true
