apiVersion: skaffold/v1
kind: Config
metadata:
  name: analyses
deploy:
  kubectl:
    manifests:
    - k8s/analyses.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/analyses
  local: {}
