apiVersion: apps/v1
kind: Deployment
metadata:
  name: iplant-groups
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: iplant-groups
  strategy:
    rollingUpdate:
      maxSurge: 200%
  template:
    metadata:
      labels:
        de-app: iplant-groups
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: de-app
                    operator: In
                    values:
                      - iplant-groups
              topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: gpg-files
          secret:
            secretName: gpg-keys
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: iplant-groups.properties
                path: iplant-groups.properties
      containers:
        - name: iplant-groups
          image: "harbor.cyverse.org/de/iplant-groups"
          resources:
            requests:
              cpu: "160m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "3000m"
              memory: "2Gi"
              ephemeral-storage: "1Gi"
          args:
            - --config
            - /etc/iplant/de/iplant-groups.properties
          volumeMounts:
            - name: gpg-files
              mountPath: /etc/iplant/crypto
              readOnly: true
            - name: service-configs
              mountPath: /etc/iplant/de
              readOnly: true
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: timezone
                  key: timezone
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: java-tool-options
                  key: low
            - name: OTEL_TRACES_EXPORTER
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_TRACES_EXPORTER
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_EXPORTER_JAEGER_ENDPOINT
          ports:
            - name: listen-port
              containerPort: 60000
          livenessProbe:
            httpGet:
              path: /
              port: 60000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 60000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /
              port: 60000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: iplant-groups
spec:
  selector:
    de-app: iplant-groups
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
