apiVersion: skaffold/v1
kind: Config
metadata:
  name: dewey
deploy:
  kubectl:
    manifests:
    - k8s/dewey.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/dewey
  local: {}
