apiVersion: skaffold/v3
kind: Config
metadata:
  name: discoenv-analyses
build:
  artifacts:
    - image: harbor.cyverse.org/de/discoenv-analyses
  platforms:
    - "linux/amd64"
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - k8s/discoenv-analyses.yml
deploy:
  kubectl: {}
