apiVersion: skaffold/v3
kind: Config
metadata:
  name: permissions
build:
  artifacts:
    - image: harbor.cyverse.org/de/permissions
  platforms:
    - linux/amd64
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - k8s/permissions.yml
deploy:
  kubectl: {}
