apiVersion: skaffold/v1
kind: Config
metadata:
  name: templeton
deploy:
  kubectl:
    manifests:
    - k8s/templeton-incremental.yml
    - k8s/templeton-periodic.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/templeton
  local: {}
