apiVersion: skaffold/v1
kind: Config
metadata:
  name: subscriptions
deploy:
  kubectl:
    manifests:
    - k8s/subscriptions.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/subscriptions
  local: {}
