apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptions
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: subscriptions
  template:
    metadata:
      labels:
        de-app: subscriptions
    spec:
      serviceAccount: configurator
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: de-app
                    operator: In
                    values:
                      - subscriptions
              topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: jobservices.yml
                path: service.yml
        - name: nats-client-tls
          secret:
            secretName: nats-client-tls
        - name: nats-services-creds
          secret:
            secretName: nats-services-creds
        - name: nats-configuration
          emptyDir: {}
      containers:
        - name: subscriptions
          image: harbor.cyverse.org/de/subscriptions
          args:
            - "--log-level=debug"
          env:
            - name: QMS_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: QMS_DATABASE_URI
            - name: QMS_NATS_CLUSTER
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: NATS_URLS
            - name: QMS_USERNAME_SUFFIX
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: USERNAME_SUFFIX
            - name: OTEL_TRACES_EXPORTER
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_TRACES_EXPORTER
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
          resources:
            requests:
              cpu: "1m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: timezone
              mountPath: /etc/timezone
              subPath: timezone
            - name: service-configs
              mountPath: /etc/cyverse/de/configs
              readOnly: true
            - name: nats-client-tls
              mountPath: /etc/nats/tls
              readOnly: true
            - name: nats-services-creds
              mountPath: /etc/nats/creds
              readOnly: true
            - name: nats-configuration
              mountPath: /etc/cyverse/de/env
              readOnly: true
          ports:
            - name: listen-port
              containerPort: 60000
          livenessProbe:
            httpGet:
              path: /
              port: 60000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 60000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: subscriptions
spec:
  selector:
    de-app: subscriptions
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
