apiVersion: skaffold/v3
kind: Config
metadata:
  name: job-status-listener
build:
  artifacts:
    - image: harbor.cyverse.org/de/job-status-listener
  platforms:
    - "linux/amd64"
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - k8s/job-status-listener.yml
deploy:
  kubectl: {}
