apiVersion: skaffold/v1
kind: Config
metadata:
  name: info-typer
deploy:
  kubectl:
    manifests:
    - k8s/info-typer.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/info-typer
  local: {}
