apiVersion: batch/v1
kind: Job
metadata:
  name: de-database
spec:
  ttlSecondsAfterFinished: 259200
  template:
    metadata:
      name: de-database
    spec:
      restartPolicy: Never
      containers:
        - name: update-de-db
          image: harbor.cyverse.org/de/de-database
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "245Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "500m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: timezone
                  key: timezone
            - name: DE_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: DE_DATABASE_URI
          args:
            - "-database"
            - "$(DE_DATABASE_URI)"
            - "-path"
            - "/migrations"
            - "up"
