apiVersion: skaffold/v1
kind: Config
metadata:
  name: de-mailer
deploy:
  kubectl:
    manifests:
      - k8s/de-mailer.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: harbor.cyverse.org/de/de-mailer
  local: {}
