apiVersion: skaffold/v3
kind: Config
metadata:
  name: grouper-dockerfile
build:
  artifacts:
    - image: harbor.cyverse.org/de/grouper
      docker:
        dockerfile: Dockerfile
  platforms:
    - "linux/amd64"
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - k8s/grouper-loader.yml
    - k8s/grouper-ws.yml
deploy:
  kubectl: {}
