apiVersion: skaffold/v1
kind: Config
metadata:
  name: grouper-dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/grouper-loader.yml
      - k8s/grouper-ws.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: harbor.cyverse.org/de/grouper
      docker:
        dockerfile: Dockerfile
  local: {}
