apiVersion: skaffold/v1
kind: Config
metadata:
  name: bulk-typer
deploy:
  kubectl:
    manifests:
    - k8s/bulk-typer.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/bulk-typer
  local: {}
