apiVersion: apps/v1
kind: Deployment
metadata:
  name: infosquito2
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: infosquito2
  template:
    metadata:
      labels:
        de-app: infosquito2
    spec:
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: infosquito2.yml
                path: infosquito2.yml
      containers:
      - name: infosquito2
        image: harbor.cyverse.org/de/infosquito2
        resources:
          requests:
            cpu: "1028m"
            memory: "128Mi"
          limits:
            cpu: "1028m"
            memory: "512Mi"
        env:
          - name: OTEL_TRACES_EXPORTER
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_TRACES_EXPORTER
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
        args:
          - --mode
          - periodic
          - --config
          - /etc/iplant/de/infosquito2.yml
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: timezone
            mountPath: /etc/timezone
            subPath: timezone
          - name: service-configs
            mountPath: /etc/iplant/de
            readOnly: true
