apiVersion: apps/v1
kind: Deployment
metadata:
  name: infosquito2
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: infosquito2
  template:
    metadata:
      labels:
        de-app: infosquito2
    spec:
      restartPolicy: Always
      volumes:
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: infosquito2.yml
                path: infosquito2.yml
      containers:
        - name: infosquito2
          image: harbor.cyverse.org/de/infosquito2
          resources:
            requests:
              cpu: "1028m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "1028m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
          env:
            - name: OTEL_TRACES_EXPORTER
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_TRACES_EXPORTER
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
          args:
            - --mode
            - periodic
            - --config
            - /etc/iplant/de/infosquito2.yml
          volumeMounts:
            - name: service-configs
              mountPath: /etc/iplant/de
              readOnly: true
