apiVersion: skaffold/v1
kind: Config
metadata:
  name: async-tasks
deploy:
  kubectl:
    manifests:
    - k8s/async-tasks.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/async-tasks
  local: {}
