apiVersion: batch/v1
kind: Job
metadata:
  name: monitoring-db
spec:
  ttlSecondsAfterFinished: 259200
  template:
    metadata:
      name: monitoring-db
    spec:
      restartPolicy: Never
      containers:
      - name: update-monitoring-db
        image: harbor.cyverse.org/de/monitoring-db
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "256m"
            memory: "128Mi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "512m"
            memory: "256Mi"
            ephemeral-storage: "1Gi"
        env:
          - name: MONITORING_DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: configs
                key: MONITORING_DATABASE_URI
        args: ["-database", "$(MONITORING_DATABASE_URI)", "-path", "/migrations", "up"]
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: timezone
            mountPath: /etc/timezone
            subPath: timezone
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
