apiVersion: apps/v1
kind: Deployment
metadata:
  name: kifshare
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: kifshare
  strategy:
    rollingUpdate:
      maxSurge: 200%
  template:
    metadata:
      labels:
        de-app: kifshare
    spec:
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: kifshare.properties
                path: kifshare.properties
      containers:
      - name: kifshare
        image: harbor.cyverse.org/de/kifshare
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: timezone
            mountPath: /etc/timezone
            subPath: timezone
          - name: service-configs
            mountPath: /etc/iplant/de
            readOnly: true
        resources:
          requests:
            cpu: "160m"
            memory: "512Mi"
          limits:
            cpu: "640m"
            memory: "2Gi"
        args:
          - --config
          - /etc/iplant/de/kifshare.properties
        env:
          - name: JAVA_TOOL_OPTIONS
            valueFrom:
              configMapKeyRef:
                name: java-tool-options
                key: low
          - name: OTEL_TRACES_EXPORTER
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_TRACES_EXPORTER
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_EXPORTER_JAEGER_ENDPOINT
        ports:
          - name: listen-port
            containerPort: 60000
        livenessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
        startupProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kifshare
spec:
  selector:
    de-app: kifshare
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
