apiVersion: v1
kind: ConfigMap
metadata:
  name: timezone
  labels:
    app: user-portal
data:
  timezone: America/Phoenix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-portal
  labels:
    app: user-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-portal
  template:
    metadata:
      labels:
        app: user-portal
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - user-portal
              topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: config-volume
          secret:
            secretName: service-configs
            items:
              - key: portal2.json
                path: portal2.json
      containers:
        - name: portal
          image: harbor.cyverse.org/de/portal2
          imagePullPolicy: Always
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: timezone
                  key: timezone
            - name: CONFIG_PATH
              value: "/etc/cyverse/portal2/portal2.json"
            - name: NODE_ENV
              value: "production"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/cyverse/portal2
              readOnly: true
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/ready
              port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: user-portal
spec:
  selector:
    app: user-portal
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
