apiVersion: skaffold/v3
kind: Config
metadata:
  name: check-resource-access
build:
  artifacts:
    - image: harbor.cyverse.org/de/check-resource-access
  platforms:
    - "linux/amd64"
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - k8s/check-resource-access.yml
deploy:
  kubectl: {}
