apiVersion: skaffold/v1
kind: Config
metadata:
  name: qms-adapter
deploy:
  kubectl:
    manifests:
    - k8s/qms-adapter.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/qms-adapter
  local: {}
