apiVersion: skaffold/v1
kind: Config
metadata:
  name: kifshare
deploy:
  kubectl:
    manifests:
    - k8s/kifshare.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/kifshare
  local: {}
