apiVersion: skaffold/v3
kind: Config
metadata:
  name: kifshare
build:
  artifacts:
    - image: harbor.cyverse.org/de/kifshare
  tagPolicy:
    gitCommit: {}
  local: {}
  platforms:
    - "linux/amd64"
manifests:
  rawYaml:
    - k8s/kifshare.yml
deploy:
  kubectl: {}
