apiVersion: apps/v1
kind: Deployment
metadata:
  name: requests
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: requests
  template:
    metadata:
      labels:
        de-app: requests
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: de-app
                    operator: In
                    values:
                      - requests
              topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: jobservices.yml
                path: jobservices.yml
      containers:
        - name: requests
          image: harbor.cyverse.org/de/requests
          resources:
            requests:
              cpu: "1m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"
          env:
            - name: OTEL_TRACES_EXPORTER
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_TRACES_EXPORTER
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
          args:
            - --config
            - /etc/iplant/de/jobservices.yml
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: timezone
              mountPath: /etc/timezone
              subPath: timezone
            - name: service-configs
              mountPath: /etc/iplant/de
              readOnly: true
          ports:
            - name: listen-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: requests
spec:
  selector:
    de-app: requests
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
