apiVersion: skaffold/v1
kind: Config
metadata:
  name: app-exposer
deploy:
  kubectl:
    manifests:
    - k8s/app-exposer.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/app-exposer
  local: {}
