apiVersion: skaffold/v3
kind: Config
metadata:
  name: app-exposer
build:
  artifacts:
    - image: harbor.cyverse.org/de/app-exposer
  platforms:
    - "linux/amd64"
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - k8s/app-exposer.yml
deploy:
  kubectl: {}
