apiVersion: skaffold/v3
kind: Config
metadata:
  name: group-propagator
build:
  artifacts:
    - image: harbor.cyverse.org/de/group-propagator
  tagPolicy:
    gitCommit: {}
  local: {}
  platforms:
    - "linux/amd64"
manifests:
  rawYaml:
    - k8s/group-propagator.yml
deploy:
  kubectl: {}
