apiVersion: skaffold/v1
kind: Config
metadata:
  name: group-propagator 
deploy:
  kubectl:
    manifests:
    - k8s/group-propagator.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/group-propagator
  local: {}
