apiVersion: apps/v1
kind: Deployment
metadata:
  name: de-webhooks
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: de-webhooks
  template:
    metadata:
      labels:
        de-app: de-webhooks
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: de-app
                    operator: In
                    values:
                      - de-webhooks
              topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: webhooks.yml
                path: webhooks.yml
      containers:
        - name: de-webhooks
          image: harbor.cyverse.org/de/de-webhooks
          volumeMounts:
            - name: service-configs
              mountPath: /etc/iplant/de
              readOnly: true
          resources:
            requests:
              cpu: "160m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "960m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"
          args:
            - --config
            - /etc/iplant/de/webhooks.yml
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: timezone
                  key: timezone
            - name: OTEL_TRACES_EXPORTER
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_TRACES_EXPORTER
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
