apiVersion: skaffold/v1
kind: Config
metadata:
  name: event-recorder
deploy:
  kubectl:
    manifests:
      - k8s/event-recorder.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: harbor.cyverse.org/de/event-recorder
  local: {}
