apiVersion: skaffold/v3
kind: Config
metadata:
  name: event-recorder
build:
  artifacts:
    - image: harbor.cyverse.org/de/event-recorder
  platforms:
    - linux/amd64
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - k8s/event-recorder.yml
deploy:
  kubectl: {}
