apiVersion: skaffold/v1
kind: Config
metadata:
  name: sonora
deploy:
  kubectl:
    manifests:
      - k8s/sonora.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: harbor.cyverse.org/de/sonora
  local: {}
