apiVersion: skaffold/v3
kind: Config
metadata:
    name: ai-sandboxes-ui
build:
    artifacts:
        - image: harbor.cyverse.org/de/ai-sandboxes-ui
    platforms:
        - linux/amd64
    tagPolicy:
        gitCommit: {}
    local: {}
manifests:
    rawYaml:
        - k8s/ai-sandboxes-ui.yml
deploy:
    kubectl: {}
