apiVersion: skaffold/v1
kind: Config
metadata:
  name: search
deploy:
  kubectl:
    manifests:
    - k8s/search.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/search
  local: {}
