apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-info
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: user-info
  template:
    metadata:
      labels:
        de-app: user-info
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: de-app
                    operator: In
                    values:
                      - user-info
              topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: jobservices.yml
                path: jobservices.yml
      containers:
        - name: user-info
          image: harbor.cyverse.org/de/user-info
          resources:
            requests:
              cpu: "1m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: timezone
                  key: timezone
            - name: OTEL_TRACES_EXPORTER
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_TRACES_EXPORTER
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
          args:
            - --config
            - /etc/iplant/de/jobservices.yml
          volumeMounts:
            - name: service-configs
              mountPath: /etc/iplant/de
              readOnly: true
          ports:
            - name: listen-port
              containerPort: 60000
          livenessProbe:
            httpGet:
              path: /
              port: 60000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 60000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: user-info
spec:
  selector:
    de-app: user-info
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
