apiVersion: skaffold/v3
kind: Config
metadata:
  name: email-requests
build:
  artifacts:
    - image: harbor.cyverse.org/de/email-requests
  platforms:
    - "linux/amd64"
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - k8s/email-requests.yml
deploy:
  kubectl: {}
