apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-conductor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-conductor

  template:
    metadata:
      labels:
        app: portal-conductor
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - portal-conductor
              topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: config-volume
          secret:
            secretName: service-configs
            items:
              - key: portal-conductor.json
                path: portal-conductor.json
        - name: ssl-certs
          secret:
            secretName: portal-conductor-ssl
      containers:
        - name: portal-conductor
          image: harbor.cyverse.org/de/portal-conductor
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /etc/cyverse/portal-conductor
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: timezone
                  key: timezone
            - name: PORTAL_CONDUCTOR_CONFIG
              value: "/etc/cyverse/portal-conductor/portal-conductor.json"
          ports:
            - name: listen-port
              containerPort: 8000
            - name: https-port
              containerPort: 8443
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: portal-conductor
spec:
  selector:
    app: portal-conductor
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: listen-port
    - name: https
      protocol: TCP
      port: 443
      targetPort: https-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp-proxy
  template:
    metadata:
      labels:
        app: smtp-proxy
    spec:
      hostNetwork: true
      restartPolicy: Always
      containers:
        - name: smtp-proxy
          image: harbor.cyverse.org/de/smtp-proxy:latest
          imagePullPolicy: Always
          ports:
            - name: smtp
              containerPort: 2525
              protocol: TCP
            - name: stats
              containerPort: 8404
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            tcpSocket:
              port: 2525
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 2525
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: smtp-proxy
spec:
  selector:
    app: smtp-proxy
  ports:
    - name: smtp
      protocol: TCP
      port: 2525
      targetPort: smtp
    - name: stats
      protocol: TCP
      port: 8404
      targetPort: stats
