apiVersion: skaffold/v1
kind: Config
metadata:
  name: data-usage-api
deploy:
  kubectl:
    manifests:
    - k8s/data-usage-api.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/data-usage-api
  local: {}
