apiVersion: skaffold/v1
kind: Config
metadata:
  name: discoenv-users
deploy:
  kubectl:
    manifests:
    - k8s/discoenv-users.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/discoenv-users
