apiVersion: skaffold/v3
kind: Config
metadata:
  name: discoenv-users
build:
  artifacts:
    - image: harbor.cyverse.org/de/discoenv-users
  platforms:
    - "linux/amd64"
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - k8s/discoenv-users.yml
deploy:
  kubectl: {}
