apiVersion: skaffold/v1
kind: Config
metadata:
  name: infosquito2
deploy:
  kubectl:
    manifests:
    - k8s/infosquito2.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/infosquito2
  local: {}
