apiVersion: skaffold/v1
kind: Config
metadata:
  name: job-status-recorder
deploy:
  kubectl:
    manifests:
    - k8s/job-status-recorder.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/job-status-recorder
  local: {}
