apiVersion: skaffold/v1
kind: Config
metadata:
  name: vice-status-listener
deploy:
  kubectl:
    manifests:
    - k8s/vice-status-listener.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/vice-status-listener
  local: {}
