apiVersion: skaffold/v3
kind: Config
metadata:
  name: clockwork
build:
  artifacts:
    - image: harbor.cyverse.org/de/clockwork
  platforms:
    - "linux/amd64"
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - k8s/clockwork.yml
deploy:
  kubectl: {}
