apiVersion: skaffold/v1
kind: Config
metadata:
  name: clockwork
deploy:
  kubectl:
    manifests:
    - k8s/clockwork.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/clockwork
  local: {}
