apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-ldap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-ldap
  template:
    metadata:
      labels:
        app: portal-ldap
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - portal-ldap
              topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      containers:
        - name: portal-ldap
          image: harbor.cyverse.org/de/portal-ldap
          env:
            - name: LDAP_URL
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: LDAP_URL
            - name: LDAP_USER
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: LDAP_USER
            - name: LDAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: LDAP_PASSWORD
            - name: LDAP_BASE_DN
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: LDAP_PASSWORD
          ports:
            - name: listen-port
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: portal-ldap
spec:
  selector:
    app: portal-ldap
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
