apiVersion: skaffold/v1
kind: Config
metadata:
  name: de-webhooks
deploy:
  kubectl:
    manifests:
    - k8s/de-webhooks.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/de-webhooks
  local: {}
