apiVersion: skaffold/v3
kind: Config
metadata:
  name: iplant-groups
build:
  artifacts:
    - image: harbor.cyverse.org/de/iplant-groups
  platforms:
    - "linux/amd64"
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - k8s/iplant-groups.yml
deploy:
  kubectl: {}
