apiVersion: skaffold/v1
kind: Config
metadata:
  name: iplant-groups
deploy:
  kubectl:
    manifests:
    - k8s/iplant-groups.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/iplant-groups
  local: {}
