apiVersion: skaffold/v1
kind: Config
metadata:
  name: user-info
deploy:
  kubectl:
    manifests:
    - k8s/user-info.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/user-info
  local: {}
