apiVersion: skaffold/v1
kind: Config
metadata:
  name: monitoring-db
deploy:
  kubectl:
    manifests:
      - k8s/monitoring-db.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/monitoring-db
  local: {}
