apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-usage-api
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: data-usage-api
  template:
    metadata:
      labels:
        de-app: data-usage-api
        app: de
    spec:
      serviceAccount: configurator
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: de-app
                    operator: In
                    values:
                      - data-usage-api
              topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: data-usage-api.yml
                path: data-usage-api.yml
        - name: nats-client-tls
          secret:
            secretName: nats-client-tls
        - name: nats-services-creds
          secret:
            secretName: nats-services-creds
      containers:
        - name: data-usage-api
          image: harbor.cyverse.org/de/data-usage-api
          resources:
            requests:
              cpu: "1m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: timezone
                  key: timezone
            - name: OTEL_TRACES_EXPORTER
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_TRACES_EXPORTER
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
            - name: DISCOENV_NATS_CLUSTER
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: NATS_URLS
          ports:
            - name: listen-port
              containerPort: 60000
          volumeMounts:
            - name: service-configs
              mountPath: /etc/iplant/de
              readOnly: true
            - name: nats-client-tls
              mountPath: /etc/nats/tls
              readOnly: true
            - name: nats-services-creds
              mountPath: /etc/nats/creds
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 60000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 60000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: data-usage-api
spec:
  selector:
    de-app: data-usage-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
