apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-resource-access
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: check-resource-access
  template:
    metadata:
      labels:
        de-app: check-resource-access
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: de-app
                    operator: In
                    values:
                      - check-resource-access
              topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      containers:
        - name: check-resource-access
          image: harbor.cyverse.org/de/check-resource-access
          resources:
            requests:
              cpu: "1m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: timezone
                  key: timezone
            - name: OTEL_TRACES_EXPORTER
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_TRACES_EXPORTER
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
          ports:
            - name: listen-port
              containerPort: 60000
          livenessProbe:
            httpGet:
              path: /debug/vars
              port: 60000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /debug/vars
              port: 60000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: check-resource-access
spec:
  selector:
    de-app: check-resource-access
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
