apiVersion: skaffold/v1
kind: Config
metadata:
  name: metadata
deploy:
  kubectl:
    manifests:
    - k8s/metadata.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/metadata
  local: {}
