apiVersion: skaffold/v3
kind: Config
metadata:
  name: maintenance-page
build:
  artifacts:
    - image: harbor.cyverse.org/de/maintenance-page
  platforms:
    - "linux/amd64"
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - k8s/maintenance-page.yml
deploy:
  kubectl: {}
